### ISSUE TITLE
Looks like Production has two instances of "No Games Available"

### ISSUE THREAD

**Issue by amarkpark** [FallGambit/fall_gambit#47]
Working locally with current Develop branch I find that my local Develop environment has no "No Games Available" option on the welcome page, whereas the Production up on Heroku has TWO of the "No Games Available" options. I tried the Production site in the incognito window to remove caching as a potential variable and loaded it on my tablet as well, and all had the same result.

![screen shot 2015-12-11 at 7 21 21 pm](https://cloud.githubusercontent.com/assets/13741014/11759275/f05de5c6-a03c-11e5-9a59-87f1ab3ea99a.png)

![screen shot 2015-12-11 at 7 21 29 pm](https://cloud.githubusercontent.com/assets/13741014/11759277/f7d6e3a2-a03c-11e5-8c34-6a1f0b15e34e.png)

Having a user signed in did not appear to change this result.

**Comment by jeffgerlach** [comment]
Merged #54 which removed the "no game available" and create game button, though there were still 2 empty div squares in their place. I ran `heroku run rails console` and manually deleted the 2 offending instances. Once we get some more functionality merged into develop, I recommend we flush the database out and start new games so that we have all the fields in the models set up correctly and (hopefully) won't have issues like this.
